### ISSUE TITLE
Avoiding type piracy for `DistributionMeasure` implementations

### ISSUE THREAD

**Issue by cscherrer** [oschulz/DistributionMeasures.jl#13]
The docs say
```
Avoid calling `DistributionMeasure(d::Distribution)` directly. Instead, use `AbstractMeasure(d::Distribution)` to allow for specialized `Distribution` to `AbstractMeasure` conversions.
```

`AbstractMeasure` is defined in MeasureBase. But in most cases, the result of `AbstractMeasure(d::Distribution)` will be defined in MeasureTheory. So this `AbstractMeasure` method will have to be defined in MT or downstream from that.

This is type piracy, though with the tight connections between MB and MT I think it would count as "licensed" type piracy. @oschulz what do you think of this? Should I be adding these methods to MT?

**Comment by oschulz** [comment]
> I think it would count as "licensed" type piracy.

Yes, this is "officially licensed" type piracy, just like implementing the measure interface for `Distribution` in DistributionMeasures.jl.

> Should I be adding these methods to MT?

Which methods? `AbstractMeasure(::Distribution)`? Uh wait, why would MT need to add this as well?

**Comment by cscherrer** [comment]
> Uh wait, why would MT need to add this as well?

For a given Distribution, we only need the corresponding `AbstractMeasure` method in one package. I'm just trying to understand which package that will be.

For example, we'll need to implement `AbstractMeasure(::Distributions.MvNormal)`, which should return a `::MeasureTheory.MvNormal`. But that requires either
1. The method is in a package downstream from MeasureTheory (don't see much point in this)
2. The method is in MeasureTheory itself, or
3. MeasureTheory is refactored somehow

**Comment by oschulz** [comment]
> we'll need to implement AbstractMeasure(::Distributions.MvNormal)

But this is what DistributionMeasures.jl does.

> which should return a ::MeasureTheory.MvNormal

The idea was that it would, in general, return a `DistributionMeasure`.

> The method is in MeasureTheory

We could do that do, returning a `MeasureTheory.MvNormal`, if we would move the distribution-related measures up from MeasureTheory.jl to DistributionMeasures.jl, maybe?

**Comment by cscherrer** [comment]
Oh, right :facepalm: 

Somehow I got thinking this would map a Distribution to something defined entirely in terms of measures, instead of just being in terms of a wrapper.

**Comment by oschulz** [comment]
> Somehow I got thinking this would map a Distribution to something defined entirely in terms of measures

We could certainly try evolve more in that direction in the future (as far as deps allow).
